import { type MappedTheme, mapVscodeTheme } from './vscode'

/**
 * 내장 VS Code 테마 프리셋. 실제 VS Code 테마 JSON과 같은 형식으로 정의해
 * 매핑 파이프라인을 통과시킨다(파이프라인 상시 검증). 색값은 각 테마의
 * 공개 팔레트 핵심 표면 기준이며, 원 저작물은 MIT/오픈 라이선스다.
 * 정렬: 다크 → 라이트.
 */

export const PRESET_THEME_JSONS: Array<{ id: string; json: Record<string, unknown> }> = [
  {
    id: 'preset-dracula',
    json: {
      name: 'Dracula',
      type: 'dark',
      colors: {
        'editor.background': '#282a36',
        'editor.foreground': '#f8f8f2',
        'sideBar.background': '#21222c',
        'sideBar.foreground': '#f8f8f2',
        'editorGroupHeader.noTabsBackground': '#191a21',
        descriptionForeground: '#b8bac4',
        'editorGroup.border': '#191a21',
        'button.background': '#bd93f9',
        'button.foreground': '#282a36',
        'button.hoverBackground': '#caa7fc',
        focusBorder: '#bd93f9',
        'terminal.ansiGreen': '#50fa7b',
        'terminal.ansiYellow': '#f1fa8c',
        'terminal.ansiRed': '#ff5555',
        'gitDecoration.addedResourceForeground': '#50fa7b',
        'gitDecoration.deletedResourceForeground': '#ff5555',
        'gitDecoration.modifiedResourceForeground': '#ffb86c',
        'diffEditor.insertedTextBackground': '#50fa7b26',
        'diffEditor.removedTextBackground': '#ff555526',
        'textCodeBlock.background': '#1e2029',
        'editorWidget.background': '#21222c',
      },
    },
  },
  {
    id: 'preset-one-dark',
    json: {
      name: 'One Dark',
      type: 'dark',
      colors: {
        'editor.background': '#282c34',
        'editor.foreground': '#abb2bf',
        'sideBar.background': '#21252b',
        'sideBar.foreground': '#abb2bf',
        'editorGroupHeader.noTabsBackground': '#21252b',
        descriptionForeground: '#9da5b4',
        'editorGroup.border': '#181a1f',
        'button.background': '#61afef',
        'button.foreground': '#282c34',
        'button.hoverBackground': '#7cbcf5',
        focusBorder: '#61afef',
        'terminal.ansiGreen': '#98c379',
        'terminal.ansiYellow': '#e5c07b',
        'terminal.ansiRed': '#e06c75',
        'gitDecoration.addedResourceForeground': '#98c379',
        'gitDecoration.deletedResourceForeground': '#e06c75',
        'gitDecoration.modifiedResourceForeground': '#e5c07b',
        'diffEditor.insertedTextBackground': '#98c37926',
        'diffEditor.removedTextBackground': '#e06c7526',
        'textCodeBlock.background': '#21252b',
        'editorWidget.background': '#21252b',
      },
    },
  },
  {
    id: 'preset-tokyo-night',
    json: {
      name: 'Tokyo Night',
      type: 'dark',
      colors: {
        'editor.background': '#1a1b26',
        'editor.foreground': '#a9b1d6',
        'sideBar.background': '#16161e',
        'sideBar.foreground': '#a9b1d6',
        'editorGroupHeader.noTabsBackground': '#16161e',
        descriptionForeground: '#a9b1d6',
        'editorGroup.border': '#1a1b26',
        'button.background': '#7aa2f7',
        'button.foreground': '#1a1b26',
        'button.hoverBackground': '#7dcfff',
        focusBorder: '#7aa2f7',
        'terminal.ansiGreen': '#9ece6a',
        'terminal.ansiYellow': '#e0af68',
        'terminal.ansiRed': '#f7768e',
        'gitDecoration.addedResourceForeground': '#9ece6a',
        'gitDecoration.deletedResourceForeground': '#f7768e',
        'gitDecoration.modifiedResourceForeground': '#e0af68',
        'diffEditor.insertedTextBackground': '#9ece6a26',
        'diffEditor.removedTextBackground': '#f7768e26',
        'textCodeBlock.background': '#16161e',
        'editorWidget.background': '#16161e',
      },
    },
  },
  {
    id: 'preset-nord',
    json: {
      name: 'Nord',
      type: 'dark',
      colors: {
        'editor.background': '#2e3440',
        'editor.foreground': '#d8dee9',
        'sideBar.background': '#3b4252',
        'sideBar.foreground': '#eceff4',
        'editorGroupHeader.noTabsBackground': '#3b4252',
        descriptionForeground: '#d8dee9',
        'editorGroup.border': '#3b4252',
        'button.background': '#88c0d0',
        'button.foreground': '#2e3440',
        'button.hoverBackground': '#8fbcbb',
        focusBorder: '#88c0d0',
        'terminal.ansiGreen': '#a3be8c',
        'terminal.ansiYellow': '#ebcb8b',
        'terminal.ansiRed': '#bf616a',
        'gitDecoration.addedResourceForeground': '#a3be8c',
        'gitDecoration.deletedResourceForeground': '#bf616a',
        'gitDecoration.modifiedResourceForeground': '#ebcb8b',
        'diffEditor.insertedTextBackground': '#a3be8c26',
        'diffEditor.removedTextBackground': '#bf616a26',
        'textCodeBlock.background': '#272c36',
        'editorWidget.background': '#3b4252',
      },
    },
  },
  {
    id: 'preset-monokai',
    json: {
      name: 'Monokai',
      type: 'dark',
      colors: {
        'editor.background': '#272822',
        'editor.foreground': '#f8f8f2',
        'sideBar.background': '#1e1f1c',
        'sideBar.foreground': '#f8f8f2',
        'editorGroupHeader.noTabsBackground': '#1e1f1c',
        descriptionForeground: '#bcbcab',
        'editorGroup.border': '#1e1f1c',
        'button.background': '#a6e22e',
        'button.foreground': '#272822',
        'button.hoverBackground': '#b8ef41',
        focusBorder: '#a6e22e',
        'terminal.ansiGreen': '#a6e22e',
        'terminal.ansiYellow': '#e6db74',
        'terminal.ansiRed': '#f92672',
        'gitDecoration.addedResourceForeground': '#a6e22e',
        'gitDecoration.deletedResourceForeground': '#f92672',
        'gitDecoration.modifiedResourceForeground': '#e6db74',
        'diffEditor.insertedTextBackground': '#a6e22e26',
        'diffEditor.removedTextBackground': '#f9267226',
        'textCodeBlock.background': '#1e1f1c',
        'editorWidget.background': '#1e1f1c',
      },
    },
  },
  {
    id: 'preset-gruvbox-dark',
    json: {
      name: 'Gruvbox Dark',
      type: 'dark',
      colors: {
        'editor.background': '#282828',
        'editor.foreground': '#ebdbb2',
        'sideBar.background': '#3c3836',
        'sideBar.foreground': '#ebdbb2',
        'editorGroupHeader.noTabsBackground': '#32302f',
        descriptionForeground: '#bdae93',
        'editorGroup.border': '#3c3836',
        'button.background': '#83a598',
        'button.foreground': '#282828',
        'button.hoverBackground': '#8ec07c',
        focusBorder: '#83a598',
        'terminal.ansiGreen': '#b8bb26',
        'terminal.ansiYellow': '#fabd2f',
        'terminal.ansiRed': '#fb4934',
        'gitDecoration.addedResourceForeground': '#b8bb26',
        'gitDecoration.deletedResourceForeground': '#fb4934',
        'gitDecoration.modifiedResourceForeground': '#fabd2f',
        'diffEditor.insertedTextBackground': '#b8bb2626',
        'diffEditor.removedTextBackground': '#fb493426',
        'textCodeBlock.background': '#32302f',
        'editorWidget.background': '#3c3836',
      },
    },
  },
  {
    id: 'preset-solarized-dark',
    json: {
      name: 'Solarized Dark',
      type: 'dark',
      colors: {
        'editor.background': '#002b36',
        'editor.foreground': '#839496',
        'sideBar.background': '#073642',
        'sideBar.foreground': '#93a1a1',
        'editorGroupHeader.noTabsBackground': '#073642',
        descriptionForeground: '#93a1a1',
        'editorGroup.border': '#073642',
        'button.background': '#268bd2',
        'button.foreground': '#eee8d5',
        'button.hoverBackground': '#2aa198',
        focusBorder: '#268bd2',
        'terminal.ansiGreen': '#859900',
        'terminal.ansiYellow': '#b58900',
        'terminal.ansiRed': '#dc322f',
        'gitDecoration.addedResourceForeground': '#859900',
        'gitDecoration.deletedResourceForeground': '#dc322f',
        'gitDecoration.modifiedResourceForeground': '#b58900',
        'diffEditor.insertedTextBackground': '#8599002a',
        'diffEditor.removedTextBackground': '#dc322f2a',
        'textCodeBlock.background': '#073642',
        'editorWidget.background': '#073642',
      },
    },
  },
  {
    id: 'preset-github-dark',
    json: {
      name: 'GitHub Dark',
      type: 'dark',
      colors: {
        'editor.background': '#0d1117',
        'editor.foreground': '#c9d1d9',
        'sideBar.background': '#161b22',
        'sideBar.foreground': '#c9d1d9',
        'editorGroupHeader.noTabsBackground': '#161b22',
        descriptionForeground: '#8b949e',
        'editorGroup.border': '#30363d',
        'button.background': '#58a6ff',
        'button.foreground': '#0d1117',
        'button.hoverBackground': '#79b8ff',
        focusBorder: '#58a6ff',
        'terminal.ansiGreen': '#3fb950',
        'terminal.ansiYellow': '#d29922',
        'terminal.ansiRed': '#f85149',
        'gitDecoration.addedResourceForeground': '#3fb950',
        'gitDecoration.deletedResourceForeground': '#f85149',
        'gitDecoration.modifiedResourceForeground': '#d29922',
        'diffEditor.insertedTextBackground': '#3fb95026',
        'diffEditor.removedTextBackground': '#f8514926',
        'textCodeBlock.background': '#161b22',
        'editorWidget.background': '#161b22',
      },
    },
  },
  {
    id: 'preset-catppuccin-mocha',
    json: {
      name: 'Catppuccin Mocha',
      type: 'dark',
      colors: {
        'editor.background': '#1e1e2e',
        'editor.foreground': '#cdd6f4',
        'sideBar.background': '#181825',
        'sideBar.foreground': '#cdd6f4',
        'editorGroupHeader.noTabsBackground': '#11111b',
        descriptionForeground: '#a5adcb',
        'editorGroup.border': '#313244',
        'button.background': '#89b4fa',
        'button.foreground': '#1e1e2e',
        'button.hoverBackground': '#74c7ec',
        focusBorder: '#89b4fa',
        'terminal.ansiGreen': '#a6e3a1',
        'terminal.ansiYellow': '#f9e2af',
        'terminal.ansiRed': '#f38ba8',
        'gitDecoration.addedResourceForeground': '#a6e3a1',
        'gitDecoration.deletedResourceForeground': '#f38ba8',
        'gitDecoration.modifiedResourceForeground': '#f9e2af',
        'diffEditor.insertedTextBackground': '#a6e3a126',
        'diffEditor.removedTextBackground': '#f38ba826',
        'textCodeBlock.background': '#11111b',
        'editorWidget.background': '#181825',
      },
    },
  },
  {
    id: 'preset-rose-pine',
    json: {
      name: 'Rosé Pine',
      type: 'dark',
      colors: {
        'editor.background': '#191724',
        'editor.foreground': '#e0def4',
        'sideBar.background': '#1f1d2e',
        'sideBar.foreground': '#e0def4',
        'editorGroupHeader.noTabsBackground': '#1f1d2e',
        descriptionForeground: '#908caa',
        'editorGroup.border': '#26233a',
        'button.background': '#c4a7e7',
        'button.foreground': '#191724',
        'button.hoverBackground': '#ebbcba',
        focusBorder: '#c4a7e7',
        'terminal.ansiGreen': '#9ccfd8',
        'terminal.ansiYellow': '#f6c177',
        'terminal.ansiRed': '#eb6f92',
        'gitDecoration.addedResourceForeground': '#9ccfd8',
        'gitDecoration.deletedResourceForeground': '#eb6f92',
        'gitDecoration.modifiedResourceForeground': '#f6c177',
        'diffEditor.insertedTextBackground': '#9ccfd826',
        'diffEditor.removedTextBackground': '#eb6f9226',
        'textCodeBlock.background': '#1f1d2e',
        'editorWidget.background': '#1f1d2e',
      },
    },
  },
  {
    id: 'preset-solarized-light',
    json: {
      name: 'Solarized Light',
      type: 'light',
      colors: {
        'editor.background': '#fdf6e3',
        'editor.foreground': '#586e75',
        'sideBar.background': '#eee8d5',
        'sideBar.foreground': '#657b83',
        'editorGroupHeader.noTabsBackground': '#eee8d5',
        descriptionForeground: '#93a1a1',
        'editorGroup.border': '#eee8d5',
        'button.background': '#268bd2',
        'button.foreground': '#fdf6e3',
        'button.hoverBackground': '#1f6fb2',
        focusBorder: '#268bd2',
        'terminal.ansiGreen': '#859900',
        'terminal.ansiYellow': '#b58900',
        'terminal.ansiRed': '#dc322f',
        'gitDecoration.addedResourceForeground': '#859900',
        'gitDecoration.deletedResourceForeground': '#dc322f',
        'gitDecoration.modifiedResourceForeground': '#b58900',
        'diffEditor.insertedTextBackground': '#8599001a',
        'diffEditor.removedTextBackground': '#dc322f1a',
        'textCodeBlock.background': '#eee8d5',
        'editorWidget.background': '#eee8d5',
      },
    },
  },
  {
    id: 'preset-github-light',
    json: {
      name: 'GitHub Light',
      type: 'light',
      colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#24292f',
        'sideBar.background': '#f6f8fa',
        'sideBar.foreground': '#24292f',
        'editorGroupHeader.noTabsBackground': '#f6f8fa',
        descriptionForeground: '#57606a',
        'editorGroup.border': '#d0d7de',
        'button.background': '#0969da',
        'button.foreground': '#ffffff',
        'button.hoverBackground': '#0550ae',
        focusBorder: '#0969da',
        'terminal.ansiGreen': '#1a7f37',
        'terminal.ansiYellow': '#9a6700',
        'terminal.ansiRed': '#cf222e',
        'gitDecoration.addedResourceForeground': '#1a7f37',
        'gitDecoration.deletedResourceForeground': '#cf222e',
        'gitDecoration.modifiedResourceForeground': '#9a6700',
        'diffEditor.insertedTextBackground': '#1a7f371a',
        'diffEditor.removedTextBackground': '#cf222e1a',
        'textCodeBlock.background': '#f6f8fa',
        'editorWidget.background': '#f6f8fa',
      },
    },
  },
  {
    id: 'preset-atom-one-light',
    json: {
      name: 'Atom One Light',
      type: 'light',
      colors: {
        'editor.background': '#fafafa',
        'editor.foreground': '#383a42',
        'sideBar.background': '#f0f0f0',
        'sideBar.foreground': '#383a42',
        'editorGroupHeader.noTabsBackground': '#f0f0f0',
        descriptionForeground: '#7a7a7a',
        'editorGroup.border': '#dcdcdc',
        'button.background': '#4078f2',
        'button.foreground': '#ffffff',
        'button.hoverBackground': '#335eeb',
        focusBorder: '#4078f2',
        'terminal.ansiGreen': '#50a14f',
        'terminal.ansiYellow': '#c18401',
        'terminal.ansiRed': '#e45649',
        'gitDecoration.addedResourceForeground': '#50a14f',
        'gitDecoration.deletedResourceForeground': '#e45649',
        'gitDecoration.modifiedResourceForeground': '#c18401',
        'diffEditor.insertedTextBackground': '#50a14f1a',
        'diffEditor.removedTextBackground': '#e456491a',
        'textCodeBlock.background': '#f0f0f0',
        'editorWidget.background': '#f0f0f0',
      },
    },
  },
  {
    id: 'preset-catppuccin-latte',
    json: {
      name: 'Catppuccin Latte',
      type: 'light',
      colors: {
        'editor.background': '#eff1f5',
        'editor.foreground': '#4c4f69',
        'sideBar.background': '#e6e9ef',
        'sideBar.foreground': '#4c4f69',
        'editorGroupHeader.noTabsBackground': '#e6e9ef',
        descriptionForeground: '#6c6f85',
        'editorGroup.border': '#bcc0cc',
        'button.background': '#1e66f5',
        'button.foreground': '#ffffff',
        'button.hoverBackground': '#04a5e5',
        focusBorder: '#1e66f5',
        'terminal.ansiGreen': '#40a02b',
        'terminal.ansiYellow': '#df8e1d',
        'terminal.ansiRed': '#d20f39',
        'gitDecoration.addedResourceForeground': '#40a02b',
        'gitDecoration.deletedResourceForeground': '#d20f39',
        'gitDecoration.modifiedResourceForeground': '#df8e1d',
        'diffEditor.insertedTextBackground': '#40a02b1a',
        'diffEditor.removedTextBackground': '#d20f391a',
        'textCodeBlock.background': '#e6e9ef',
        'editorWidget.background': '#e6e9ef',
      },
    },
  },
]

/** 매핑은 가볍지만 매 렌더마다 다시 하지 않도록 모듈 캐시로 둔다. */
let cached: MappedTheme[] | null = null

export function presetThemes(): MappedTheme[] {
  if (!cached) {
    cached = PRESET_THEME_JSONS.map(({ id, json }) => mapVscodeTheme(json, id))
  }
  return cached
}
