packages: []

allowBuilds:
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  lefthook: set this to true or false

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild

strictDepBuilds: false
